
services:
  redis:
    image: redis:7-alpine
    container_name: job-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api-gateway:
    image: kubernetes-assignment-api-gateway:v1
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      redis:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: services/worker/Dockerfile
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      redis:
        condition: service_healthy

  stats:
    build:
      context: .
      dockerfile: services/stats/Dockerfile
    container_name: stats-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - .env.production
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis-data:
