/**
 * Status code for http request
 */

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  NOT_FOUND_ID: 422,
  BAD_GATEWAY: 502,
  GATEWAY_TIMEOUT:504,
  SERVICE_UNAVAILABLE:503
};

export default HTTP_STATUS;
